- name: Configure system
  hosts: localhost
  environment:
    "{{ env }}"
  pre_tasks:
    - name: Check sudo permission
      become: true
      command: "echo You have sudo permission!"
      register: hi
  roles:
    - configure
