---
download_path: "{{ ansible_env.HOME }}/Downloads/"
ansible_path: "/etc/ansible/"

env: {
  ANSIBLE_NOCOWS: 1,
  EDITOR: vim
}

alias: {
  dc: "docker-compose"
}

keys: {
  # RVM
  # "hkp://keys.gnupg.net": "409B6B1796C275462A1703113804BB82D39DC0E3"
}

keys_url:
  # Docker
  - "https://download.docker.com/linux/ubuntu/gpg"
  # VSCode
  - "https://packages.microsoft.com/keys/microsoft.asc"

# Repositories to add to sources.list
sources_list:
  # Docker
  - "deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable"
  # VSCode
  - "deb [arch=amd64] https://packages.microsoft.com/repos/vscode stable main"

# Remote deb file to install once
single_use_debs: {
  "chrome.deb": "https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb"
}

# Packages to install via apt
packages:
  - build-essential
  - python-gpgme # Dropbox requirement
  - libssl-dev
  - openssl
  - virtualenv
  - docker-ce
  - code
  - vim

gsettings:
  - {
      "name": "org.cinnamon.desktop.interface clock-use-24h",
      "value": "true"
    }
  - {
      "name": "org.cinnamon.desktop.interface clock-show-date",
      "value": "true"
    }
  - {
      "name": "org.cinnamon.settings-daemon.peripherals.touchscreen orientation-lock",
      "value": "true"
    }
  - {
      "name": "org.cinnamon.muffin tile-maximize",
      "value": "true"
    }
