---
- name: Create Ansible config directory
  become: true
  file:
    path: "{{ ansible_path }}"
    state: directory

- name: Create Ansible config file
  become: true
  copy:
    src: ansible-conf.ini
    dest: /etc/ansible/ansible.cfg
