---
- name: Set git email
  git_config:
    name: user.email
    value: "{{ _email }}"
    scope: global

- name: Set git name
  git_config:
    name: user.name
    value: "{{ _name }}"
    scope: global
