---
- name: Set git email
  git_config:
    name: user.email
    value: "{{ _email }}"
    scope: global

- name: Set git name
  git_config:
    name: user.name
    value: "{{ _name }}"
    scope: global

- name: Use new push/branch behavior
  git_config:
    name: push.default
    value: simple
    scope: global

- name: Create the .gitignore_global file
  copy:
    src: .gitignore_global
    dest: "~/.gitignore_global"

- name: Add the global git ignore
  git_config:
    name: core.excludesfile
    value: "~/.gitignore_global"
    scope: global
