---
- name: Install remote deb packages
  apt:
    deb: "{{ item.value }}"
  with_dict: "{{ fetch_install_deb }}"

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items: "{{ packages }}"
