---
- name: Install deb packages
  become: true
  apt:
    deb: "{{ item.dest }}"
  with_items: "{{ remote_debs.results }}"

- name: Install packages
  become: true
  apt:
    name: "{{ item }}"
    state: latest
    force: yes
  with_items: "{{ packages }}"

- name: Custom installs (eg. curl sh | bash)
  become: true
  command: "{{ item }}"
  with_items: "{{ curl_sh }}"
