---
- name: Add Key Servers
  become: true
  apt_key:
    keyserver: "{{ item.key }}"
    id: "{{ item.value }}"
  with_dict: "{{ keys }}"

- name: Add Key Servers (by URL)
  become: true
  apt_key:
    url: "{{ item }}"
  with_items: "{{ keys_url }}"

- name: Add entries to sources.list
  become: true
  apt_repository: 
    repo: "{{ item }}"
  with_items: "{{ sources_list }}"

- name: Create Download directory
  file:
    path: "{{ download_path }}"
    state: directory

- name: Download deb files
  get_url:
    url: "{{ item.value }}"
    dest: "{{ download_path }}{{ item.key }}"
  with_dict: "{{ single_use_debs }}"
  register: remote_debs

- name: Update
  become: true
  apt:
    update_cache: true

- name: Upgrade
  become: true
  apt:
    upgrade: full # Do not use full. We want the "safe" upgrade.
