---
- name: Get latest Python versions (2 and 3)
  vars:
    versions:
      - 2
      - 3
  get_latest_python_versions:
    versions: "{{ versions }}"
  register: versions

- name: Download Python files
  get_url:
    url: "https://www.python.org/ftp/python/{{ item }}/Python-{{ item }}.tar.xz"
    dest: "{{ download_path }}"
  with_items: "{{ versions.val }}"
  register: pythons

- name: Extract TARs
  unarchive:
    src: "{{ item.dest }}"
    dest: "{{ download_path }}"
  with_items: "{{ pythons.results }}"
  register: pythons

- name: Install Python versions (./configure)
  command: "./configure --prefix=/opt/python{{ item.item.item }}"
  args:
    chdir: "{{ item.dest }}Python-{{ item.item.item }}/"
  with_items: "{{ pythons.results }}"

- name: Install Python versions (make)
  command: "make"
  args:
    chdir: "{{ item.dest }}Python-{{ item.item.item }}/"
  with_items: "{{ pythons.results }}"

- name: Install Python versions (make install)
  become: true
  command: "make install"
  args:
    chdir: "{{ item.dest }}Python-{{ item.item.item }}/"
  with_items: "{{ pythons.results }}"

- name: Remove TARs
  become: true
  file:
    path: "{{ item.dest }}Python-{{ item.item.item }}"
    state: absent
  with_items: "{{ pythons.results }}"
