---
- name: Set environment variables
  lineinfile:
    dest: "~/.bashrc"
    line: "export {{ item.key }}={{ item.value }}"
  with_dict: "{{ env }}"

- name: Set environment variables
  lineinfile:
    dest: "~/.bashrc"
    line: "alias {{ item.key }}=\"{{ item.value }}\""
  with_dict: "{{ alias }}"
