---
- name: Add user to docker group for non-sudo access
 become: true
 user:
   name: "{{ lookup('env', 'USER') }}"
   group: docker
   append: true

- name: Set proper gsettings
  become: true
  become_user: "{{ lookup('env', 'SUDO_USER') }}"
  command: "gsettings set {{ item.name }} {{ item.value }}"
  with_items: "{{ gsettings }}"
